# Generated by Django 2.1.7 on 2019-03-26 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=64, verbose_name='订单号')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品总金额')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='免付金额')),
                ('pay_method', models.SmallIntegerField(choices=[('wexin', '微信'), ('zhifubao', '支付宝'), ('orther', '其他')], default=1, verbose_name='支付方式')),
                ('status', models.CharField(choices=[('waitpay', '待支付'), ('success', '已支付'), ('cancel', '已取消')], default='待支付', max_length=32, verbose_name='订单状态')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.Course', verbose_name='下单商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.User', verbose_name='下单用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'order',
                'ordering': ['c_time'],
            },
        ),
    ]
