# Generated by Django 2.1.7 on 2019-03-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_method',
            field=models.SmallIntegerField(choices=[('微信', '微信'), ('支付宝', '支付宝'), ('其他', '其他')], default=1, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('待支付', '待支付'), ('已支付', '已支付'), ('已取消', '已取消')], default='待支付', max_length=32, verbose_name='订单状态'),
        ),
    ]
