# Generated by Django 2.1.7 on 2019-03-28 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20190328_1109'),
        ('order', '0003_auto_20190327_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='usercourse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='course.UserCourse', verbose_name='课程用户关联'),
        ),
    ]
