# Generated by Django 2.1.7 on 2019-03-28 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20190328_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='course.Course', verbose_name='下单商品'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='免付金额'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_method',
            field=models.CharField(choices=[('wexin', '微信'), ('zhifubao', '支付宝'), ('orther', '其他')], default='其他', max_length=64, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waitpay', '待支付'), ('success', '已支付'), ('cancel', '已取消')], default='待支付', max_length=32, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='商品总金额'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='user.User', verbose_name='下单用户'),
        ),
    ]
