# Generated by Django 2.1.7 on 2019-03-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, null=True)),
                ('url', models.CharField(max_length=128, null=True)),
                ('banner', models.FileField(upload_to='upload/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'banner图',
                'verbose_name_plural': 'banner图',
                'db_table': 'banner',
                'ordering': ['id'],
            },
        ),
    ]
