# Generated by Django 2.1.7 on 2019-03-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='url',
        ),
        migrations.AddField(
            model_name='banner',
            name='pic',
            field=models.FileField(null=True, upload_to='upload/pic/banner/%Y/%m/%d'),
        ),
    ]
