# Generated by Django 2.1.7 on 2019-03-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_auto_20190327_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='pic',
            field=models.FileField(null=True, upload_to='upload/pic/banner/%Y/%m/%d', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=128, null=True, verbose_name='标题'),
        ),
    ]
