# Generated by Django 2.1.7 on 2019-03-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20190327_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('over', '已完成'), ('unover', '未完成')], default='未完成', max_length=32),
        ),
    ]
