# Generated by Django 2.1.7 on 2019-03-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20190329_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='do_time',
            field=models.CharField(max_length=128, verbose_name='完成时间'),
        ),
    ]
