# Generated by Django 2.1.7 on 2019-03-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20190326_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='stick',
            field=models.CharField(choices=[('置顶', '置顶'), ('未置顶', '未置顶')], default='未置顶', max_length=32),
        ),
    ]
