# Generated by Django 2.1.7 on 2019-03-29 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20190327_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='content2',
            field=models.CharField(max_length=500, null=True, verbose_name='简介2'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='content',
            field=models.CharField(max_length=500, verbose_name='简介1'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='label',
            field=models.CharField(max_length=128, verbose_name='头衔'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=128, verbose_name='是否姓名'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='stick',
            field=models.CharField(choices=[('stick', '置顶'), ('unstick', '未置顶')], default='未置顶', max_length=32, verbose_name='是否推荐'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='user.User', verbose_name='关联用户'),
        ),
    ]
