# Generated by Django 2.1.7 on 2019-03-26 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_course_user'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', '开放'), ('close', '关闭')], default='open', max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.Course', verbose_name='课程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户课程',
                'verbose_name_plural': '用户课程',
                'db_table': 'usercourse',
                'ordering': ['c_time'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.ManyToManyField(through='user.UserCourse', to='course.Course'),
        ),
    ]
