# Generated by Django 2.1.7 on 2019-03-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190327_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pic',
            field=models.FileField(null=True, upload_to='upload/pic/user/%Y/%m/%d'),
        ),
    ]
