# Generated by Django 2.1.7 on 2019-03-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paypassword',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telphone',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
