# Generated by Django 2.1.7 on 2019-03-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190329_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='paypassword',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name='支付密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.FileField(null=True, upload_to='upload/pic/user/%Y/%m/%d', verbose_name='用户图片'),
        ),
        migrations.AlterField(
            model_name='user',
            name='realname',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telphone',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name='电话'),
        ),
    ]
