# Generated by Django 2.1.7 on 2019-03-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20190327_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pic',
            field=models.FileField(null=True, upload_to='upload/pic/course/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('training:', '精品'), ('heig', '高级'), ('start', '基础')], default='免费', max_length=32),
        ),
    ]
