# Generated by Django 2.1.7 on 2019-03-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20190327_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('精品', '精品训练营'), ('高级', '高级课程'), ('基础', '基础课程')], default='免费', max_length=32),
        ),
    ]
