# Generated by Django 2.1.7 on 2019-03-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20190327_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='class_type',
            field=models.CharField(choices=[('视频', '视频'), ('问题', '问题'), ('文章', '文章'), ('资料', '资料')], default='视频', max_length=32),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='status',
            field=models.CharField(choices=[('已发布', '已发布'), ('未发布', '未发布')], default='未发布', max_length=32),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='type',
            field=models.CharField(choices=[('章', '章'), ('节', '节')], default='节', max_length=32),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('已发布', '已发布'), ('未发布', '未发布')], default='未发布', max_length=32),
        ),
        migrations.AlterField(
            model_name='course',
            name='stick',
            field=models.CharField(choices=[('置顶', '置顶'), ('未置顶', '未置顶')], default='未置顶', max_length=32),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='status',
            field=models.CharField(choices=[('开放', '开放'), ('关闭', '关闭')], default='open', max_length=32),
        ),
    ]
