# Generated by Django 2.1.7 on 2019-03-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20190327_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='class_type',
            field=models.CharField(choices=[('video', '视频'), ('question', '问题'), ('article', '文章'), ('data', '资料')], default='视频', max_length=32),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='status',
            field=models.CharField(choices=[('public', '已发布'), ('unpublic', '未发布')], default='未发布', max_length=32),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='type',
            field=models.CharField(choices=[('chapter', '章'), ('section', '节')], default='节', max_length=32),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('training:', '精品'), ('heig', '高级'), ('start', '基础')], default='免费', max_length=32),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('public', '已发布'), ('unpublic', '未发布')], default='未发布', max_length=32),
        ),
        migrations.AlterField(
            model_name='course',
            name='stick',
            field=models.CharField(choices=[('stick', '置顶'), ('unstick', '未置顶')], default='未置顶', max_length=32),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='status',
            field=models.CharField(choices=[('open', '开放'), ('close', '关闭')], default='open', max_length=32),
        ),
    ]
