# Generated by Django 2.1.7 on 2019-03-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20190327_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('training', '精品'), ('heigh', '高级'), ('start', '基础')], default='免费', max_length=32),
        ),
    ]
