# Generated by Django 2.1.7 on 2019-03-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20190328_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='dopercent',
            field=models.CharField(default='0', max_length=32, verbose_name='完成度'),
        ),
    ]
