# Generated by Django 2.1.7 on 2019-03-28 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_catalog_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='contentid',
        ),
    ]
