# Generated by Django 2.1.7 on 2019-03-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_remove_catalog_contentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
        migrations.RemoveField(
            model_name='video',
            name='url',
        ),
        migrations.AddField(
            model_name='video',
            name='pic',
            field=models.FileField(null=True, upload_to='upload/video/course/%Y/%m/%d'),
        ),
    ]
