# Generated by Django 2.1.7 on 2019-03-29 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_auto_20190328_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pic', models.FileField(null=True, upload_to='upload/pic/object/%Y/%m/%d')),
                ('title', models.CharField(max_length=128)),
                ('content', models.CharField(max_length=500)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('u_time', models.DateTimeField(auto_now=True)),
                ('Course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='course.Course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'db_table': 'object',
                'ordering': ['c_time'],
            },
        ),
    ]
