# Generated by Django 2.1.7 on 2019-03-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='url',
            field=models.CharField(max_length=128, null=True, verbose_name='课程页面url'),
        ),
    ]
