# Generated by Django 2.1.7 on 2019-03-29 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_course_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='content',
        ),
        migrations.AddField(
            model_name='catalog',
            name='capter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='course.Catalog', verbose_name='所属章节'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='isproject',
            field=models.CharField(choices=[('yes', '是'), ('no', '否')], default='是否是项目', max_length=32),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='title',
            field=models.CharField(max_length=128, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='course',
            name='content',
            field=models.CharField(max_length=500, verbose_name='内容描述'),
        ),
        migrations.AlterField(
            model_name='course',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='价钱'),
        ),
        migrations.AlterField(
            model_name='course',
            name='last_time',
            field=models.DateTimeField(verbose_name='上次开课时间'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('training', '精品'), ('heigh', '高级'), ('start', '基础')], default='免费', max_length=32, verbose_name='课程类别'),
        ),
        migrations.AlterField(
            model_name='course',
            name='max_people_num',
            field=models.IntegerField(default=0, verbose_name='最多人数'),
        ),
        migrations.AlterField(
            model_name='course',
            name='next_time',
            field=models.DateTimeField(verbose_name='下次开课时间'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('public', '已发布'), ('unpublic', '未发布')], default='未发布', max_length=32, verbose_name='课程状态'),
        ),
        migrations.AlterField(
            model_name='course',
            name='stick',
            field=models.CharField(choices=[('stick', '置顶'), ('unstick', '未置顶')], default='未置顶', max_length=32, verbose_name='是否推荐'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=128, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='object',
            name='Course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='course.Course', verbose_name='所属课程'),
        ),
        migrations.AlterField(
            model_name='object',
            name='content',
            field=models.CharField(max_length=500, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='object',
            name='pic',
            field=models.FileField(null=True, upload_to='upload/pic/object/%Y/%m/%d', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='object',
            name='title',
            field=models.CharField(max_length=128, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='video',
            name='over_time',
            field=models.CharField(max_length=128, verbose_name='完成最短用时'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(null=True, upload_to='upload/video/course/%Y/%m/%d', verbose_name='视频'),
        ),
    ]
