# Generated by Django 2.1.7 on 2019-03-29 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_auto_20190329_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='capter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='course.Catalog', verbose_name='所属章节'),
        ),
    ]
