# Generated by Django 2.1.7 on 2019-04-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_auto_20190329_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='label',
            field=models.CharField(choices=[('start', '基础知识'), ('startandproject', '基础和项目实践')], default='基础知识', max_length=32, verbose_name='课程状态'),
        ),
        migrations.AddField(
            model_name='course',
            name='live_time',
            field=models.DateTimeField(null=True, verbose_name='学习有效期'),
        ),
    ]
