# Generated by Django 2.1.7 on 2019-04-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_auto_20190402_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='label',
        ),
        migrations.AddField(
            model_name='catalog',
            name='label',
            field=models.CharField(choices=[('start', '基础知识'), ('startandproject', '基础和项目实践')], default='基础知识', max_length=32, verbose_name='章节标签'),
        ),
    ]
