# Generated by Django 2.1.7 on 2019-04-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_auto_20190402_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='content',
            field=models.CharField(max_length=256, null=True, verbose_name='章节内容描述'),
        ),
    ]
